Reset timer at 9am
BoOmka/discord-pidor-bot pull request #1
Opened 2021-12-29 18:37 UTC by krestkrest

Reset timer at 9am to prevent the time window slipping every day during the work week.
Also upgraded jest version for security reasons (npm asked me to do that).

2021-12-30 05:57 UTC, surranov requested changes

2021-12-30 05:57 UTC, surranov commented on test.js
> +})
new line at end of line

2021-12-30 05:57 UTC, surranov commented on src/Game.js
>  module.exports = Game;
new line at end of line

2021-12-30 09:29 UTC, krestkrest commented on test.js
> +})
fixed

2021-12-30 09:29 UTC, krestkrest commented on src/Game.js
>  module.exports = Game;
fixed

2021-12-30 09:32 UTC, surranov approved these changes

2022-01-10 09:12 UTC, merged

2022-01-10 09:49 UTC, ecrofeg commented
Огонь бля